//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Controles.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Controles.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Controles: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Controles()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Controles"",
    ""maps"": [
        {
            ""name"": ""PajarosVScerdos"",
            ""id"": ""7f570bfd-9d82-40a1-8d8e-89d4d7b10b63"",
            ""actions"": [
                {
                    ""name"": ""Presionado"",
                    ""type"": ""Button"",
                    ""id"": ""d771fde6-dc39-4ab5-ba0c-a3c64b07b84c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Posicion"",
                    ""type"": ""Value"",
                    ""id"": ""5a877ceb-ebf9-46e6-ac0a-5d9a0b700e96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PotenciaMas"",
                    ""type"": ""Button"",
                    ""id"": ""46a6a5cd-80b6-4d5a-9f6c-69e6973b1893"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""697d80fe-b6c8-4841-9041-a67bbbb411ca"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Presionado"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""409abc97-4049-45b5-a566-cf2c76b71732"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Posicion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41f02aaa-7b71-4d1f-8af1-f43f694aeb14"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PotenciaMas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PajarosVScerdos
        m_PajarosVScerdos = asset.FindActionMap("PajarosVScerdos", throwIfNotFound: true);
        m_PajarosVScerdos_Presionado = m_PajarosVScerdos.FindAction("Presionado", throwIfNotFound: true);
        m_PajarosVScerdos_Posicion = m_PajarosVScerdos.FindAction("Posicion", throwIfNotFound: true);
        m_PajarosVScerdos_PotenciaMas = m_PajarosVScerdos.FindAction("PotenciaMas", throwIfNotFound: true);
    }

    ~@Controles()
    {
        UnityEngine.Debug.Assert(!m_PajarosVScerdos.enabled, "This will cause a leak and performance issues, Controles.PajarosVScerdos.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PajarosVScerdos
    private readonly InputActionMap m_PajarosVScerdos;
    private List<IPajarosVScerdosActions> m_PajarosVScerdosActionsCallbackInterfaces = new List<IPajarosVScerdosActions>();
    private readonly InputAction m_PajarosVScerdos_Presionado;
    private readonly InputAction m_PajarosVScerdos_Posicion;
    private readonly InputAction m_PajarosVScerdos_PotenciaMas;
    /// <summary>
    /// Provides access to input actions defined in input action map "PajarosVScerdos".
    /// </summary>
    public struct PajarosVScerdosActions
    {
        private @Controles m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PajarosVScerdosActions(@Controles wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PajarosVScerdos/Presionado".
        /// </summary>
        public InputAction @Presionado => m_Wrapper.m_PajarosVScerdos_Presionado;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVScerdos/Posicion".
        /// </summary>
        public InputAction @Posicion => m_Wrapper.m_PajarosVScerdos_Posicion;
        /// <summary>
        /// Provides access to the underlying input action "PajarosVScerdos/PotenciaMas".
        /// </summary>
        public InputAction @PotenciaMas => m_Wrapper.m_PajarosVScerdos_PotenciaMas;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PajarosVScerdos; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PajarosVScerdosActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PajarosVScerdosActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PajarosVScerdosActions" />
        public void AddCallbacks(IPajarosVScerdosActions instance)
        {
            if (instance == null || m_Wrapper.m_PajarosVScerdosActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PajarosVScerdosActionsCallbackInterfaces.Add(instance);
            @Presionado.started += instance.OnPresionado;
            @Presionado.performed += instance.OnPresionado;
            @Presionado.canceled += instance.OnPresionado;
            @Posicion.started += instance.OnPosicion;
            @Posicion.performed += instance.OnPosicion;
            @Posicion.canceled += instance.OnPosicion;
            @PotenciaMas.started += instance.OnPotenciaMas;
            @PotenciaMas.performed += instance.OnPotenciaMas;
            @PotenciaMas.canceled += instance.OnPotenciaMas;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PajarosVScerdosActions" />
        private void UnregisterCallbacks(IPajarosVScerdosActions instance)
        {
            @Presionado.started -= instance.OnPresionado;
            @Presionado.performed -= instance.OnPresionado;
            @Presionado.canceled -= instance.OnPresionado;
            @Posicion.started -= instance.OnPosicion;
            @Posicion.performed -= instance.OnPosicion;
            @Posicion.canceled -= instance.OnPosicion;
            @PotenciaMas.started -= instance.OnPotenciaMas;
            @PotenciaMas.performed -= instance.OnPotenciaMas;
            @PotenciaMas.canceled -= instance.OnPotenciaMas;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PajarosVScerdosActions.UnregisterCallbacks(IPajarosVScerdosActions)" />.
        /// </summary>
        /// <seealso cref="PajarosVScerdosActions.UnregisterCallbacks(IPajarosVScerdosActions)" />
        public void RemoveCallbacks(IPajarosVScerdosActions instance)
        {
            if (m_Wrapper.m_PajarosVScerdosActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PajarosVScerdosActions.AddCallbacks(IPajarosVScerdosActions)" />
        /// <seealso cref="PajarosVScerdosActions.RemoveCallbacks(IPajarosVScerdosActions)" />
        /// <seealso cref="PajarosVScerdosActions.UnregisterCallbacks(IPajarosVScerdosActions)" />
        public void SetCallbacks(IPajarosVScerdosActions instance)
        {
            foreach (var item in m_Wrapper.m_PajarosVScerdosActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PajarosVScerdosActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PajarosVScerdosActions" /> instance referencing this action map.
    /// </summary>
    public PajarosVScerdosActions @PajarosVScerdos => new PajarosVScerdosActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PajarosVScerdos" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PajarosVScerdosActions.AddCallbacks(IPajarosVScerdosActions)" />
    /// <seealso cref="PajarosVScerdosActions.RemoveCallbacks(IPajarosVScerdosActions)" />
    public interface IPajarosVScerdosActions
    {
        /// <summary>
        /// Method invoked when associated input action "Presionado" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPresionado(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Posicion" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosicion(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PotenciaMas" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPotenciaMas(InputAction.CallbackContext context);
    }
}
